//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_Client.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.17.192.53:8080/webservice/wsCheckAccountaddress")]
        public string WMS_Client_CheckAccoutServiceIService_CheckAccountServiceIService {
            get {
                return ((string)(this["WMS_Client_CheckAccoutServiceIService_CheckAccountServiceIService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sfis.phicomm.com.cn/SFIS_WEBSER/tR_Tr_Sn.asmx")]
        public string WMS_Client_tR_Tr_Sn_tR_Tr_Sn {
            get {
                return ((string)(this["WMS_Client_tR_Tr_Sn_tR_Tr_Sn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sappip.freecomm-networks.com:50000/XISOAPAdapter/MessageServlet?senderPart" +
            "y=&senderService=WMS_PRD&receiverParty=&receiverService=&interface=GoodsMvtCreat" +
            "e_OUT&interfaceNamespace=http%3A%2F%2Fphicomm.com%2FWMS%2FPI018%2FGoodsMvtCreate" +
            "")]
        public string WMS_Client_GoodsMvtCreate_OUT_GoodsMvtCreate_OUTService {
            get {
                return ((string)(this["WMS_Client_GoodsMvtCreate_OUT_GoodsMvtCreate_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sappip.freecomm-networks.com:50000/XISOAPAdapter/MessageServlet?senderPart" +
            "y=&senderService=WMS_PRD&receiverParty=&receiverService=&interface=DeliveryList_" +
            "OUT&interfaceNamespace=http%3A%2F%2Fphicomm.com%2FWMS%2FPI021%2FDeliveryList")]
        public string WMS_Client_DeliveryList_OUT_DeliveryList_OUTService {
            get {
                return ((string)(this["WMS_Client_DeliveryList_OUT_DeliveryList_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sappip.freecomm-networks.com:50000/XISOAPAdapter/MessageServlet?senderPart" +
            "y=&senderService=WMS_PRD&receiverParty=&receiverService=&interface=ReservationDe" +
            "tail_OUT&interfaceNamespace=http%3A%2F%2Fphicomm.com%2FWMS%2FPI020%2FReservation" +
            "Detail")]
        public string WMS_Client_ReservationDetail_OUT_ReservationDetail_OUTService {
            get {
                return ((string)(this["WMS_Client_ReservationDetail_OUT_ReservationDetail_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sappip.freecomm-networks.com:50000/XISOAPAdapter/MessageServlet?senderPart" +
            "y=&senderService=MES_PRD&receiverParty=&receiverService=&interface=ZPI_PIINTF_ME" +
            "S_SUBCON_PURCHASE&interfaceNamespace=urn%3Asap-com%3Adocument%3Asap%3Arfc%3Afunc" +
            "tions")]
        public string WMS_Client_ZPI_PIINTF_MES_SUBCON_PURCHASE_ZPI_PIINTF_MES_SUBCON_PURCHASEService {
            get {
                return ((string)(this["WMS_Client_ZPI_PIINTF_MES_SUBCON_PURCHASE_ZPI_PIINTF_MES_SUBCON_PURCHASEService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://wms-client.phicomm.com/WMS_WEBSER/R_Tr_Sn.asmx")]
        public string WMS_Client_WMS_WebServices_R_Tr_Sn {
            get {
                return ((string)(this["WMS_Client_WMS_WebServices_R_Tr_Sn"]));
            }
        }
    }
}
