//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Phicomm_WMS.tR_Tr_Sn {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="tR_Tr_SnSoap", Namespace="http://tempuri.org/")]
    public partial class tR_Tr_Sn : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Sel_Tr_Sn_InfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback WMS_Sel_Tr_Sn_InfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback WMS_UPDATE_TR_SNOperationCompleted;
        
        private System.Threading.SendOrPostCallback Update_TR_SNOperationCompleted;
        
        private System.Threading.SendOrPostCallback UPDATE_TR_SNOperationCompleted;
        
        private System.Threading.SendOrPostCallback Smt_SplitMaterialOperationCompleted;
        
        private System.Threading.SendOrPostCallback Sel_woId_Trsn_ListOperationCompleted;
        
        private System.Threading.SendOrPostCallback Sel_woId_Trsn_List_WinCeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSeqTrSnInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback insert_into_R_tr_snOperationCompleted;
        
        private System.Threading.SendOrPostCallback Insert_R_TrSnOperationCompleted;
        
        private System.Threading.SendOrPostCallback insert_into_R_tr_sn_detailOperationCompleted;
        
        private System.Threading.SendOrPostCallback Del_TR_SNOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_Tr_Sn_DetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback WMS_get_R_Sap_Back_ShippingOperationCompleted;
        
        private System.Threading.SendOrPostCallback WMS_RFC_ZMM_GOODSMVT_CREATE_listOperationCompleted;
        
        private System.Threading.SendOrPostCallback WMS_Insert_R_SAP_BACK_SHIPPINGOperationCompleted;
        
        private System.Threading.SendOrPostCallback WMS_Update_R_Sap_Back_ShippingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public tR_Tr_Sn() {
            this.Url = global::Phicomm_WMS.Properties.Settings.Default.WMS_Client_tR_Tr_Sn_tR_Tr_Sn;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Sel_Tr_Sn_InfoCompletedEventHandler Sel_Tr_Sn_InfoCompleted;
        
        /// <remarks/>
        public event WMS_Sel_Tr_Sn_InfoCompletedEventHandler WMS_Sel_Tr_Sn_InfoCompleted;
        
        /// <remarks/>
        public event WMS_UPDATE_TR_SNCompletedEventHandler WMS_UPDATE_TR_SNCompleted;
        
        /// <remarks/>
        public event Update_TR_SNCompletedEventHandler Update_TR_SNCompleted;
        
        /// <remarks/>
        public event UPDATE_TR_SNCompletedEventHandler UPDATE_TR_SNCompleted;
        
        /// <remarks/>
        public event Smt_SplitMaterialCompletedEventHandler Smt_SplitMaterialCompleted;
        
        /// <remarks/>
        public event Sel_woId_Trsn_ListCompletedEventHandler Sel_woId_Trsn_ListCompleted;
        
        /// <remarks/>
        public event Sel_woId_Trsn_List_WinCeCompletedEventHandler Sel_woId_Trsn_List_WinCeCompleted;
        
        /// <remarks/>
        public event GetSeqTrSnInfoCompletedEventHandler GetSeqTrSnInfoCompleted;
        
        /// <remarks/>
        public event insert_into_R_tr_snCompletedEventHandler insert_into_R_tr_snCompleted;
        
        /// <remarks/>
        public event Insert_R_TrSnCompletedEventHandler Insert_R_TrSnCompleted;
        
        /// <remarks/>
        public event insert_into_R_tr_sn_detailCompletedEventHandler insert_into_R_tr_sn_detailCompleted;
        
        /// <remarks/>
        public event Del_TR_SNCompletedEventHandler Del_TR_SNCompleted;
        
        /// <remarks/>
        public event Get_Tr_Sn_DetailCompletedEventHandler Get_Tr_Sn_DetailCompleted;
        
        /// <remarks/>
        public event WMS_get_R_Sap_Back_ShippingCompletedEventHandler WMS_get_R_Sap_Back_ShippingCompleted;
        
        /// <remarks/>
        public event WMS_RFC_ZMM_GOODSMVT_CREATE_listCompletedEventHandler WMS_RFC_ZMM_GOODSMVT_CREATE_listCompleted;
        
        /// <remarks/>
        public event WMS_Insert_R_SAP_BACK_SHIPPINGCompletedEventHandler WMS_Insert_R_SAP_BACK_SHIPPINGCompleted;
        
        /// <remarks/>
        public event WMS_Update_R_Sap_Back_ShippingCompletedEventHandler WMS_Update_R_Sap_Back_ShippingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Sel_Tr_Sn_Info", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Sel_Tr_Sn_Info(string T_sn, out string Status) {
            object[] results = this.Invoke("Sel_Tr_Sn_Info", new object[] {
                        T_sn});
            Status = ((string)(results[1]));
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void Sel_Tr_Sn_InfoAsync(string T_sn) {
            this.Sel_Tr_Sn_InfoAsync(T_sn, null);
        }
        
        /// <remarks/>
        public void Sel_Tr_Sn_InfoAsync(string T_sn, object userState) {
            if ((this.Sel_Tr_Sn_InfoOperationCompleted == null)) {
                this.Sel_Tr_Sn_InfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSel_Tr_Sn_InfoOperationCompleted);
            }
            this.InvokeAsync("Sel_Tr_Sn_Info", new object[] {
                        T_sn}, this.Sel_Tr_Sn_InfoOperationCompleted, userState);
        }
        
        private void OnSel_Tr_Sn_InfoOperationCompleted(object arg) {
            if ((this.Sel_Tr_Sn_InfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Sel_Tr_Sn_InfoCompleted(this, new Sel_Tr_Sn_InfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WMS_Sel_Tr_Sn_Info", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] WMS_Sel_Tr_Sn_Info(string T_sn, string Fields) {
            object[] results = this.Invoke("WMS_Sel_Tr_Sn_Info", new object[] {
                        T_sn,
                        Fields});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void WMS_Sel_Tr_Sn_InfoAsync(string T_sn, string Fields) {
            this.WMS_Sel_Tr_Sn_InfoAsync(T_sn, Fields, null);
        }
        
        /// <remarks/>
        public void WMS_Sel_Tr_Sn_InfoAsync(string T_sn, string Fields, object userState) {
            if ((this.WMS_Sel_Tr_Sn_InfoOperationCompleted == null)) {
                this.WMS_Sel_Tr_Sn_InfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWMS_Sel_Tr_Sn_InfoOperationCompleted);
            }
            this.InvokeAsync("WMS_Sel_Tr_Sn_Info", new object[] {
                        T_sn,
                        Fields}, this.WMS_Sel_Tr_Sn_InfoOperationCompleted, userState);
        }
        
        private void OnWMS_Sel_Tr_Sn_InfoOperationCompleted(object arg) {
            if ((this.WMS_Sel_Tr_Sn_InfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WMS_Sel_Tr_Sn_InfoCompleted(this, new WMS_Sel_Tr_Sn_InfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WMS_UPDATE_TR_SN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WMS_UPDATE_TR_SN(string Json) {
            object[] results = this.Invoke("WMS_UPDATE_TR_SN", new object[] {
                        Json});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WMS_UPDATE_TR_SNAsync(string Json) {
            this.WMS_UPDATE_TR_SNAsync(Json, null);
        }
        
        /// <remarks/>
        public void WMS_UPDATE_TR_SNAsync(string Json, object userState) {
            if ((this.WMS_UPDATE_TR_SNOperationCompleted == null)) {
                this.WMS_UPDATE_TR_SNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWMS_UPDATE_TR_SNOperationCompleted);
            }
            this.InvokeAsync("WMS_UPDATE_TR_SN", new object[] {
                        Json}, this.WMS_UPDATE_TR_SNOperationCompleted, userState);
        }
        
        private void OnWMS_UPDATE_TR_SNOperationCompleted(object arg) {
            if ((this.WMS_UPDATE_TR_SNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WMS_UPDATE_TR_SNCompleted(this, new WMS_UPDATE_TR_SNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update_TR_SN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Update_TR_SN(string R_Trsn, string R_WOID, string R_USERID, string R_STATUS, string R_RMAK1, string R_RMAK2) {
            object[] results = this.Invoke("Update_TR_SN", new object[] {
                        R_Trsn,
                        R_WOID,
                        R_USERID,
                        R_STATUS,
                        R_RMAK1,
                        R_RMAK2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Update_TR_SNAsync(string R_Trsn, string R_WOID, string R_USERID, string R_STATUS, string R_RMAK1, string R_RMAK2) {
            this.Update_TR_SNAsync(R_Trsn, R_WOID, R_USERID, R_STATUS, R_RMAK1, R_RMAK2, null);
        }
        
        /// <remarks/>
        public void Update_TR_SNAsync(string R_Trsn, string R_WOID, string R_USERID, string R_STATUS, string R_RMAK1, string R_RMAK2, object userState) {
            if ((this.Update_TR_SNOperationCompleted == null)) {
                this.Update_TR_SNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate_TR_SNOperationCompleted);
            }
            this.InvokeAsync("Update_TR_SN", new object[] {
                        R_Trsn,
                        R_WOID,
                        R_USERID,
                        R_STATUS,
                        R_RMAK1,
                        R_RMAK2}, this.Update_TR_SNOperationCompleted, userState);
        }
        
        private void OnUpdate_TR_SNOperationCompleted(object arg) {
            if ((this.Update_TR_SNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Update_TR_SNCompleted(this, new Update_TR_SNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UPDATE_TR_SN_Json", RequestElementName="UPDATE_TR_SN_Json", RequestNamespace="http://tempuri.org/", ResponseElementName="UPDATE_TR_SN_JsonResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("UPDATE_TR_SN_JsonResult")]
        public string UPDATE_TR_SN(string Json) {
            object[] results = this.Invoke("UPDATE_TR_SN", new object[] {
                        Json});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UPDATE_TR_SNAsync(string Json) {
            this.UPDATE_TR_SNAsync(Json, null);
        }
        
        /// <remarks/>
        public void UPDATE_TR_SNAsync(string Json, object userState) {
            if ((this.UPDATE_TR_SNOperationCompleted == null)) {
                this.UPDATE_TR_SNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUPDATE_TR_SNOperationCompleted);
            }
            this.InvokeAsync("UPDATE_TR_SN", new object[] {
                        Json}, this.UPDATE_TR_SNOperationCompleted, userState);
        }
        
        private void OnUPDATE_TR_SNOperationCompleted(object arg) {
            if ((this.UPDATE_TR_SNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UPDATE_TR_SNCompleted(this, new UPDATE_TR_SNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Smt_SplitMaterial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Smt_SplitMaterial(string Json) {
            this.Invoke("Smt_SplitMaterial", new object[] {
                        Json});
        }
        
        /// <remarks/>
        public void Smt_SplitMaterialAsync(string Json) {
            this.Smt_SplitMaterialAsync(Json, null);
        }
        
        /// <remarks/>
        public void Smt_SplitMaterialAsync(string Json, object userState) {
            if ((this.Smt_SplitMaterialOperationCompleted == null)) {
                this.Smt_SplitMaterialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSmt_SplitMaterialOperationCompleted);
            }
            this.InvokeAsync("Smt_SplitMaterial", new object[] {
                        Json}, this.Smt_SplitMaterialOperationCompleted, userState);
        }
        
        private void OnSmt_SplitMaterialOperationCompleted(object arg) {
            if ((this.Smt_SplitMaterialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Smt_SplitMaterialCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Sel_woId_Trsn_List", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Sel_woId_Trsn_List(string woId, string Flag) {
            object[] results = this.Invoke("Sel_woId_Trsn_List", new object[] {
                        woId,
                        Flag});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void Sel_woId_Trsn_ListAsync(string woId, string Flag) {
            this.Sel_woId_Trsn_ListAsync(woId, Flag, null);
        }
        
        /// <remarks/>
        public void Sel_woId_Trsn_ListAsync(string woId, string Flag, object userState) {
            if ((this.Sel_woId_Trsn_ListOperationCompleted == null)) {
                this.Sel_woId_Trsn_ListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSel_woId_Trsn_ListOperationCompleted);
            }
            this.InvokeAsync("Sel_woId_Trsn_List", new object[] {
                        woId,
                        Flag}, this.Sel_woId_Trsn_ListOperationCompleted, userState);
        }
        
        private void OnSel_woId_Trsn_ListOperationCompleted(object arg) {
            if ((this.Sel_woId_Trsn_ListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Sel_woId_Trsn_ListCompleted(this, new Sel_woId_Trsn_ListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Sel_woId_Trsn_List_WinCe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Sel_woId_Trsn_List_WinCe(string woId, string Flag) {
            object[] results = this.Invoke("Sel_woId_Trsn_List_WinCe", new object[] {
                        woId,
                        Flag});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void Sel_woId_Trsn_List_WinCeAsync(string woId, string Flag) {
            this.Sel_woId_Trsn_List_WinCeAsync(woId, Flag, null);
        }
        
        /// <remarks/>
        public void Sel_woId_Trsn_List_WinCeAsync(string woId, string Flag, object userState) {
            if ((this.Sel_woId_Trsn_List_WinCeOperationCompleted == null)) {
                this.Sel_woId_Trsn_List_WinCeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSel_woId_Trsn_List_WinCeOperationCompleted);
            }
            this.InvokeAsync("Sel_woId_Trsn_List_WinCe", new object[] {
                        woId,
                        Flag}, this.Sel_woId_Trsn_List_WinCeOperationCompleted, userState);
        }
        
        private void OnSel_woId_Trsn_List_WinCeOperationCompleted(object arg) {
            if ((this.Sel_woId_Trsn_List_WinCeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Sel_woId_Trsn_List_WinCeCompleted(this, new Sel_woId_Trsn_List_WinCeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSeqTrSnInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSeqTrSnInfo() {
            object[] results = this.Invoke("GetSeqTrSnInfo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSeqTrSnInfoAsync() {
            this.GetSeqTrSnInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetSeqTrSnInfoAsync(object userState) {
            if ((this.GetSeqTrSnInfoOperationCompleted == null)) {
                this.GetSeqTrSnInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSeqTrSnInfoOperationCompleted);
            }
            this.InvokeAsync("GetSeqTrSnInfo", new object[0], this.GetSeqTrSnInfoOperationCompleted, userState);
        }
        
        private void OnGetSeqTrSnInfoOperationCompleted(object arg) {
            if ((this.GetSeqTrSnInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSeqTrSnInfoCompleted(this, new GetSeqTrSnInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insert_into_R_tr_sn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string insert_into_R_tr_sn(string dicstring) {
            object[] results = this.Invoke("insert_into_R_tr_sn", new object[] {
                        dicstring});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void insert_into_R_tr_snAsync(string dicstring) {
            this.insert_into_R_tr_snAsync(dicstring, null);
        }
        
        /// <remarks/>
        public void insert_into_R_tr_snAsync(string dicstring, object userState) {
            if ((this.insert_into_R_tr_snOperationCompleted == null)) {
                this.insert_into_R_tr_snOperationCompleted = new System.Threading.SendOrPostCallback(this.Oninsert_into_R_tr_snOperationCompleted);
            }
            this.InvokeAsync("insert_into_R_tr_sn", new object[] {
                        dicstring}, this.insert_into_R_tr_snOperationCompleted, userState);
        }
        
        private void Oninsert_into_R_tr_snOperationCompleted(object arg) {
            if ((this.insert_into_R_tr_snCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insert_into_R_tr_snCompleted(this, new insert_into_R_tr_snCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insert_R_TrSn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Insert_R_TrSn(TrSnFields[] LsTsf) {
            object[] results = this.Invoke("Insert_R_TrSn", new object[] {
                        LsTsf});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Insert_R_TrSnAsync(TrSnFields[] LsTsf) {
            this.Insert_R_TrSnAsync(LsTsf, null);
        }
        
        /// <remarks/>
        public void Insert_R_TrSnAsync(TrSnFields[] LsTsf, object userState) {
            if ((this.Insert_R_TrSnOperationCompleted == null)) {
                this.Insert_R_TrSnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsert_R_TrSnOperationCompleted);
            }
            this.InvokeAsync("Insert_R_TrSn", new object[] {
                        LsTsf}, this.Insert_R_TrSnOperationCompleted, userState);
        }
        
        private void OnInsert_R_TrSnOperationCompleted(object arg) {
            if ((this.Insert_R_TrSnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Insert_R_TrSnCompleted(this, new Insert_R_TrSnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insert_into_R_tr_sn_detail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string insert_into_R_tr_sn_detail(string dicstring) {
            object[] results = this.Invoke("insert_into_R_tr_sn_detail", new object[] {
                        dicstring});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void insert_into_R_tr_sn_detailAsync(string dicstring) {
            this.insert_into_R_tr_sn_detailAsync(dicstring, null);
        }
        
        /// <remarks/>
        public void insert_into_R_tr_sn_detailAsync(string dicstring, object userState) {
            if ((this.insert_into_R_tr_sn_detailOperationCompleted == null)) {
                this.insert_into_R_tr_sn_detailOperationCompleted = new System.Threading.SendOrPostCallback(this.Oninsert_into_R_tr_sn_detailOperationCompleted);
            }
            this.InvokeAsync("insert_into_R_tr_sn_detail", new object[] {
                        dicstring}, this.insert_into_R_tr_sn_detailOperationCompleted, userState);
        }
        
        private void Oninsert_into_R_tr_sn_detailOperationCompleted(object arg) {
            if ((this.insert_into_R_tr_sn_detailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insert_into_R_tr_sn_detailCompleted(this, new insert_into_R_tr_sn_detailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Del_TR_SN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Del_TR_SN(string R_Trsn) {
            object[] results = this.Invoke("Del_TR_SN", new object[] {
                        R_Trsn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Del_TR_SNAsync(string R_Trsn) {
            this.Del_TR_SNAsync(R_Trsn, null);
        }
        
        /// <remarks/>
        public void Del_TR_SNAsync(string R_Trsn, object userState) {
            if ((this.Del_TR_SNOperationCompleted == null)) {
                this.Del_TR_SNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDel_TR_SNOperationCompleted);
            }
            this.InvokeAsync("Del_TR_SN", new object[] {
                        R_Trsn}, this.Del_TR_SNOperationCompleted, userState);
        }
        
        private void OnDel_TR_SNOperationCompleted(object arg) {
            if ((this.Del_TR_SNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Del_TR_SNCompleted(this, new Del_TR_SNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Tr_Sn_Detail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Get_Tr_Sn_Detail(string Tr_Sn) {
            object[] results = this.Invoke("Get_Tr_Sn_Detail", new object[] {
                        Tr_Sn});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_Tr_Sn_DetailAsync(string Tr_Sn) {
            this.Get_Tr_Sn_DetailAsync(Tr_Sn, null);
        }
        
        /// <remarks/>
        public void Get_Tr_Sn_DetailAsync(string Tr_Sn, object userState) {
            if ((this.Get_Tr_Sn_DetailOperationCompleted == null)) {
                this.Get_Tr_Sn_DetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Tr_Sn_DetailOperationCompleted);
            }
            this.InvokeAsync("Get_Tr_Sn_Detail", new object[] {
                        Tr_Sn}, this.Get_Tr_Sn_DetailOperationCompleted, userState);
        }
        
        private void OnGet_Tr_Sn_DetailOperationCompleted(object arg) {
            if ((this.Get_Tr_Sn_DetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Tr_Sn_DetailCompleted(this, new Get_Tr_Sn_DetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WMS_get_R_Sap_Back_Shipping", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] WMS_get_R_Sap_Back_Shipping(string JsonStr) {
            object[] results = this.Invoke("WMS_get_R_Sap_Back_Shipping", new object[] {
                        JsonStr});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void WMS_get_R_Sap_Back_ShippingAsync(string JsonStr) {
            this.WMS_get_R_Sap_Back_ShippingAsync(JsonStr, null);
        }
        
        /// <remarks/>
        public void WMS_get_R_Sap_Back_ShippingAsync(string JsonStr, object userState) {
            if ((this.WMS_get_R_Sap_Back_ShippingOperationCompleted == null)) {
                this.WMS_get_R_Sap_Back_ShippingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWMS_get_R_Sap_Back_ShippingOperationCompleted);
            }
            this.InvokeAsync("WMS_get_R_Sap_Back_Shipping", new object[] {
                        JsonStr}, this.WMS_get_R_Sap_Back_ShippingOperationCompleted, userState);
        }
        
        private void OnWMS_get_R_Sap_Back_ShippingOperationCompleted(object arg) {
            if ((this.WMS_get_R_Sap_Back_ShippingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WMS_get_R_Sap_Back_ShippingCompleted(this, new WMS_get_R_Sap_Back_ShippingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WMS_RFC_ZMM_GOODSMVT_CREATE_list", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] WMS_RFC_ZMM_GOODSMVT_CREATE_list(string ListJson) {
            object[] results = this.Invoke("WMS_RFC_ZMM_GOODSMVT_CREATE_list", new object[] {
                        ListJson});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void WMS_RFC_ZMM_GOODSMVT_CREATE_listAsync(string ListJson) {
            this.WMS_RFC_ZMM_GOODSMVT_CREATE_listAsync(ListJson, null);
        }
        
        /// <remarks/>
        public void WMS_RFC_ZMM_GOODSMVT_CREATE_listAsync(string ListJson, object userState) {
            if ((this.WMS_RFC_ZMM_GOODSMVT_CREATE_listOperationCompleted == null)) {
                this.WMS_RFC_ZMM_GOODSMVT_CREATE_listOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWMS_RFC_ZMM_GOODSMVT_CREATE_listOperationCompleted);
            }
            this.InvokeAsync("WMS_RFC_ZMM_GOODSMVT_CREATE_list", new object[] {
                        ListJson}, this.WMS_RFC_ZMM_GOODSMVT_CREATE_listOperationCompleted, userState);
        }
        
        private void OnWMS_RFC_ZMM_GOODSMVT_CREATE_listOperationCompleted(object arg) {
            if ((this.WMS_RFC_ZMM_GOODSMVT_CREATE_listCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WMS_RFC_ZMM_GOODSMVT_CREATE_listCompleted(this, new WMS_RFC_ZMM_GOODSMVT_CREATE_listCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WMS_Insert_R_SAP_BACK_SHIPPING", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WMS_Insert_R_SAP_BACK_SHIPPING(string ListJson) {
            object[] results = this.Invoke("WMS_Insert_R_SAP_BACK_SHIPPING", new object[] {
                        ListJson});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WMS_Insert_R_SAP_BACK_SHIPPINGAsync(string ListJson) {
            this.WMS_Insert_R_SAP_BACK_SHIPPINGAsync(ListJson, null);
        }
        
        /// <remarks/>
        public void WMS_Insert_R_SAP_BACK_SHIPPINGAsync(string ListJson, object userState) {
            if ((this.WMS_Insert_R_SAP_BACK_SHIPPINGOperationCompleted == null)) {
                this.WMS_Insert_R_SAP_BACK_SHIPPINGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWMS_Insert_R_SAP_BACK_SHIPPINGOperationCompleted);
            }
            this.InvokeAsync("WMS_Insert_R_SAP_BACK_SHIPPING", new object[] {
                        ListJson}, this.WMS_Insert_R_SAP_BACK_SHIPPINGOperationCompleted, userState);
        }
        
        private void OnWMS_Insert_R_SAP_BACK_SHIPPINGOperationCompleted(object arg) {
            if ((this.WMS_Insert_R_SAP_BACK_SHIPPINGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WMS_Insert_R_SAP_BACK_SHIPPINGCompleted(this, new WMS_Insert_R_SAP_BACK_SHIPPINGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WMS_Update_R_Sap_Back_Shipping", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WMS_Update_R_Sap_Back_Shipping(string ListJson, string Transaction) {
            object[] results = this.Invoke("WMS_Update_R_Sap_Back_Shipping", new object[] {
                        ListJson,
                        Transaction});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WMS_Update_R_Sap_Back_ShippingAsync(string ListJson, string Transaction) {
            this.WMS_Update_R_Sap_Back_ShippingAsync(ListJson, Transaction, null);
        }
        
        /// <remarks/>
        public void WMS_Update_R_Sap_Back_ShippingAsync(string ListJson, string Transaction, object userState) {
            if ((this.WMS_Update_R_Sap_Back_ShippingOperationCompleted == null)) {
                this.WMS_Update_R_Sap_Back_ShippingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWMS_Update_R_Sap_Back_ShippingOperationCompleted);
            }
            this.InvokeAsync("WMS_Update_R_Sap_Back_Shipping", new object[] {
                        ListJson,
                        Transaction}, this.WMS_Update_R_Sap_Back_ShippingOperationCompleted, userState);
        }
        
        private void OnWMS_Update_R_Sap_Back_ShippingOperationCompleted(object arg) {
            if ((this.WMS_Update_R_Sap_Back_ShippingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WMS_Update_R_Sap_Back_ShippingCompleted(this, new WMS_Update_R_Sap_Back_ShippingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TrSnFields {
        
        private string pO_IDField;
        
        private string tR_SNField;
        
        private string kP_NOField;
        
        private string kP_DESCField;
        
        private string vENDER_IDField;
        
        private string vENDER_NAMEField;
        
        private string dATE_CODEField;
        
        private string lOT_CODEField;
        
        private int qTYField;
        
        private string sTOCK_IDField;
        
        private string lOC_IDField;
        
        private string tANSFER_NOField;
        
        private string uRGENT_PNField;
        
        private string sTOCK_NOField;
        
        private System.DateTime sTOCK_DATEField;
        
        private string wOIDField;
        
        private string uSER_IDField;
        
        private string sTATUSField;
        
        private string rEMARK1Field;
        
        private string rEMARK2Field;
        
        private System.DateTime uPDATE_DATEField;
        
        private string fIFO_DCField;
        
        /// <remarks/>
        public string PO_ID {
            get {
                return this.pO_IDField;
            }
            set {
                this.pO_IDField = value;
            }
        }
        
        /// <remarks/>
        public string TR_SN {
            get {
                return this.tR_SNField;
            }
            set {
                this.tR_SNField = value;
            }
        }
        
        /// <remarks/>
        public string KP_NO {
            get {
                return this.kP_NOField;
            }
            set {
                this.kP_NOField = value;
            }
        }
        
        /// <remarks/>
        public string KP_DESC {
            get {
                return this.kP_DESCField;
            }
            set {
                this.kP_DESCField = value;
            }
        }
        
        /// <remarks/>
        public string VENDER_ID {
            get {
                return this.vENDER_IDField;
            }
            set {
                this.vENDER_IDField = value;
            }
        }
        
        /// <remarks/>
        public string VENDER_NAME {
            get {
                return this.vENDER_NAMEField;
            }
            set {
                this.vENDER_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string DATE_CODE {
            get {
                return this.dATE_CODEField;
            }
            set {
                this.dATE_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string LOT_CODE {
            get {
                return this.lOT_CODEField;
            }
            set {
                this.lOT_CODEField = value;
            }
        }
        
        /// <remarks/>
        public int QTY {
            get {
                return this.qTYField;
            }
            set {
                this.qTYField = value;
            }
        }
        
        /// <remarks/>
        public string STOCK_ID {
            get {
                return this.sTOCK_IDField;
            }
            set {
                this.sTOCK_IDField = value;
            }
        }
        
        /// <remarks/>
        public string LOC_ID {
            get {
                return this.lOC_IDField;
            }
            set {
                this.lOC_IDField = value;
            }
        }
        
        /// <remarks/>
        public string TANSFER_NO {
            get {
                return this.tANSFER_NOField;
            }
            set {
                this.tANSFER_NOField = value;
            }
        }
        
        /// <remarks/>
        public string URGENT_PN {
            get {
                return this.uRGENT_PNField;
            }
            set {
                this.uRGENT_PNField = value;
            }
        }
        
        /// <remarks/>
        public string STOCK_NO {
            get {
                return this.sTOCK_NOField;
            }
            set {
                this.sTOCK_NOField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime STOCK_DATE {
            get {
                return this.sTOCK_DATEField;
            }
            set {
                this.sTOCK_DATEField = value;
            }
        }
        
        /// <remarks/>
        public string WOID {
            get {
                return this.wOIDField;
            }
            set {
                this.wOIDField = value;
            }
        }
        
        /// <remarks/>
        public string USER_ID {
            get {
                return this.uSER_IDField;
            }
            set {
                this.uSER_IDField = value;
            }
        }
        
        /// <remarks/>
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        public string REMARK1 {
            get {
                return this.rEMARK1Field;
            }
            set {
                this.rEMARK1Field = value;
            }
        }
        
        /// <remarks/>
        public string REMARK2 {
            get {
                return this.rEMARK2Field;
            }
            set {
                this.rEMARK2Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime UPDATE_DATE {
            get {
                return this.uPDATE_DATEField;
            }
            set {
                this.uPDATE_DATEField = value;
            }
        }
        
        /// <remarks/>
        public string FIFO_DC {
            get {
                return this.fIFO_DCField;
            }
            set {
                this.fIFO_DCField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Sel_Tr_Sn_InfoCompletedEventHandler(object sender, Sel_Tr_Sn_InfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Sel_Tr_Sn_InfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Sel_Tr_Sn_InfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void WMS_Sel_Tr_Sn_InfoCompletedEventHandler(object sender, WMS_Sel_Tr_Sn_InfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WMS_Sel_Tr_Sn_InfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WMS_Sel_Tr_Sn_InfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void WMS_UPDATE_TR_SNCompletedEventHandler(object sender, WMS_UPDATE_TR_SNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WMS_UPDATE_TR_SNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WMS_UPDATE_TR_SNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Update_TR_SNCompletedEventHandler(object sender, Update_TR_SNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Update_TR_SNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Update_TR_SNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void UPDATE_TR_SNCompletedEventHandler(object sender, UPDATE_TR_SNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UPDATE_TR_SNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UPDATE_TR_SNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Smt_SplitMaterialCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Sel_woId_Trsn_ListCompletedEventHandler(object sender, Sel_woId_Trsn_ListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Sel_woId_Trsn_ListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Sel_woId_Trsn_ListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Sel_woId_Trsn_List_WinCeCompletedEventHandler(object sender, Sel_woId_Trsn_List_WinCeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Sel_woId_Trsn_List_WinCeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Sel_woId_Trsn_List_WinCeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetSeqTrSnInfoCompletedEventHandler(object sender, GetSeqTrSnInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSeqTrSnInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSeqTrSnInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void insert_into_R_tr_snCompletedEventHandler(object sender, insert_into_R_tr_snCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insert_into_R_tr_snCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insert_into_R_tr_snCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Insert_R_TrSnCompletedEventHandler(object sender, Insert_R_TrSnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Insert_R_TrSnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Insert_R_TrSnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void insert_into_R_tr_sn_detailCompletedEventHandler(object sender, insert_into_R_tr_sn_detailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insert_into_R_tr_sn_detailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insert_into_R_tr_sn_detailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Del_TR_SNCompletedEventHandler(object sender, Del_TR_SNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Del_TR_SNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Del_TR_SNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Get_Tr_Sn_DetailCompletedEventHandler(object sender, Get_Tr_Sn_DetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Tr_Sn_DetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Tr_Sn_DetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void WMS_get_R_Sap_Back_ShippingCompletedEventHandler(object sender, WMS_get_R_Sap_Back_ShippingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WMS_get_R_Sap_Back_ShippingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WMS_get_R_Sap_Back_ShippingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void WMS_RFC_ZMM_GOODSMVT_CREATE_listCompletedEventHandler(object sender, WMS_RFC_ZMM_GOODSMVT_CREATE_listCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WMS_RFC_ZMM_GOODSMVT_CREATE_listCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WMS_RFC_ZMM_GOODSMVT_CREATE_listCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void WMS_Insert_R_SAP_BACK_SHIPPINGCompletedEventHandler(object sender, WMS_Insert_R_SAP_BACK_SHIPPINGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WMS_Insert_R_SAP_BACK_SHIPPINGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WMS_Insert_R_SAP_BACK_SHIPPINGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void WMS_Update_R_Sap_Back_ShippingCompletedEventHandler(object sender, WMS_Update_R_Sap_Back_ShippingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WMS_Update_R_Sap_Back_ShippingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WMS_Update_R_Sap_Back_ShippingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591