//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace WMS_Client.WMS_WebServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="R_Tr_SnSoap", Namespace="http://tempuri.org/")]
    public partial class R_Tr_Sn : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetSeqTrSnAndInsertOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_Tr_SnOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_Tr_Sn_LocIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_tr_sn_currentOperationCompleted;
        
        private System.Threading.SendOrPostCallback UPDATE_TR_SNOperationCompleted;
        
        private System.Threading.SendOrPostCallback Insert_Tr_SnOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_SAP_PO_Tr_SnOperationCompleted;
        
        private System.Threading.SendOrPostCallback TrSn_Barcode_ImportOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_SAP_PO_Tr_Sn_AllOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public R_Tr_Sn() {
            this.Url = global::WMS_Client.Properties.Settings.Default.WMS_Client_WMS_WebServices_R_Tr_Sn;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetSeqTrSnAndInsertCompletedEventHandler GetSeqTrSnAndInsertCompleted;
        
        /// <remarks/>
        public event Get_Tr_SnCompletedEventHandler Get_Tr_SnCompleted;
        
        /// <remarks/>
        public event Get_Tr_Sn_LocIdCompletedEventHandler Get_Tr_Sn_LocIdCompleted;
        
        /// <remarks/>
        public event Get_tr_sn_currentCompletedEventHandler Get_tr_sn_currentCompleted;
        
        /// <remarks/>
        public event UPDATE_TR_SNCompletedEventHandler UPDATE_TR_SNCompleted;
        
        /// <remarks/>
        public event Insert_Tr_SnCompletedEventHandler Insert_Tr_SnCompleted;
        
        /// <remarks/>
        public event Delete_SAP_PO_Tr_SnCompletedEventHandler Delete_SAP_PO_Tr_SnCompleted;
        
        /// <remarks/>
        public event TrSn_Barcode_ImportCompletedEventHandler TrSn_Barcode_ImportCompleted;
        
        /// <remarks/>
        public event Delete_SAP_PO_Tr_Sn_AllCompletedEventHandler Delete_SAP_PO_Tr_Sn_AllCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSeqTrSnAndInsert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSeqTrSnAndInsert(string Json, int pring_qty, bool is_scrap, string ROWID, string STOCK_YEAR) {
            object[] results = this.Invoke("GetSeqTrSnAndInsert", new object[] {
                        Json,
                        pring_qty,
                        is_scrap,
                        ROWID,
                        STOCK_YEAR});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSeqTrSnAndInsertAsync(string Json, int pring_qty, bool is_scrap, string ROWID, string STOCK_YEAR) {
            this.GetSeqTrSnAndInsertAsync(Json, pring_qty, is_scrap, ROWID, STOCK_YEAR, null);
        }
        
        /// <remarks/>
        public void GetSeqTrSnAndInsertAsync(string Json, int pring_qty, bool is_scrap, string ROWID, string STOCK_YEAR, object userState) {
            if ((this.GetSeqTrSnAndInsertOperationCompleted == null)) {
                this.GetSeqTrSnAndInsertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSeqTrSnAndInsertOperationCompleted);
            }
            this.InvokeAsync("GetSeqTrSnAndInsert", new object[] {
                        Json,
                        pring_qty,
                        is_scrap,
                        ROWID,
                        STOCK_YEAR}, this.GetSeqTrSnAndInsertOperationCompleted, userState);
        }
        
        private void OnGetSeqTrSnAndInsertOperationCompleted(object arg) {
            if ((this.GetSeqTrSnAndInsertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSeqTrSnAndInsertCompleted(this, new GetSeqTrSnAndInsertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Tr_Sn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Get_Tr_Sn(string Json, string Fields) {
            object[] results = this.Invoke("Get_Tr_Sn", new object[] {
                        Json,
                        Fields});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_Tr_SnAsync(string Json, string Fields) {
            this.Get_Tr_SnAsync(Json, Fields, null);
        }
        
        /// <remarks/>
        public void Get_Tr_SnAsync(string Json, string Fields, object userState) {
            if ((this.Get_Tr_SnOperationCompleted == null)) {
                this.Get_Tr_SnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Tr_SnOperationCompleted);
            }
            this.InvokeAsync("Get_Tr_Sn", new object[] {
                        Json,
                        Fields}, this.Get_Tr_SnOperationCompleted, userState);
        }
        
        private void OnGet_Tr_SnOperationCompleted(object arg) {
            if ((this.Get_Tr_SnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Tr_SnCompleted(this, new Get_Tr_SnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Tr_Sn_LocId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_Tr_Sn_LocId(string Json) {
            object[] results = this.Invoke("Get_Tr_Sn_LocId", new object[] {
                        Json});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_Tr_Sn_LocIdAsync(string Json) {
            this.Get_Tr_Sn_LocIdAsync(Json, null);
        }
        
        /// <remarks/>
        public void Get_Tr_Sn_LocIdAsync(string Json, object userState) {
            if ((this.Get_Tr_Sn_LocIdOperationCompleted == null)) {
                this.Get_Tr_Sn_LocIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Tr_Sn_LocIdOperationCompleted);
            }
            this.InvokeAsync("Get_Tr_Sn_LocId", new object[] {
                        Json}, this.Get_Tr_Sn_LocIdOperationCompleted, userState);
        }
        
        private void OnGet_Tr_Sn_LocIdOperationCompleted(object arg) {
            if ((this.Get_Tr_Sn_LocIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Tr_Sn_LocIdCompleted(this, new Get_Tr_Sn_LocIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_tr_sn_current", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_tr_sn_current(int pring_qty) {
            object[] results = this.Invoke("Get_tr_sn_current", new object[] {
                        pring_qty});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_tr_sn_currentAsync(int pring_qty) {
            this.Get_tr_sn_currentAsync(pring_qty, null);
        }
        
        /// <remarks/>
        public void Get_tr_sn_currentAsync(int pring_qty, object userState) {
            if ((this.Get_tr_sn_currentOperationCompleted == null)) {
                this.Get_tr_sn_currentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_tr_sn_currentOperationCompleted);
            }
            this.InvokeAsync("Get_tr_sn_current", new object[] {
                        pring_qty}, this.Get_tr_sn_currentOperationCompleted, userState);
        }
        
        private void OnGet_tr_sn_currentOperationCompleted(object arg) {
            if ((this.Get_tr_sn_currentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_tr_sn_currentCompleted(this, new Get_tr_sn_currentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UPDATE_TR_SN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UPDATE_TR_SN(string Json) {
            object[] results = this.Invoke("UPDATE_TR_SN", new object[] {
                        Json});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UPDATE_TR_SNAsync(string Json) {
            this.UPDATE_TR_SNAsync(Json, null);
        }
        
        /// <remarks/>
        public void UPDATE_TR_SNAsync(string Json, object userState) {
            if ((this.UPDATE_TR_SNOperationCompleted == null)) {
                this.UPDATE_TR_SNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUPDATE_TR_SNOperationCompleted);
            }
            this.InvokeAsync("UPDATE_TR_SN", new object[] {
                        Json}, this.UPDATE_TR_SNOperationCompleted, userState);
        }
        
        private void OnUPDATE_TR_SNOperationCompleted(object arg) {
            if ((this.UPDATE_TR_SNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UPDATE_TR_SNCompleted(this, new UPDATE_TR_SNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insert_Tr_Sn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Insert_Tr_Sn(string Json) {
            object[] results = this.Invoke("Insert_Tr_Sn", new object[] {
                        Json});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Insert_Tr_SnAsync(string Json) {
            this.Insert_Tr_SnAsync(Json, null);
        }
        
        /// <remarks/>
        public void Insert_Tr_SnAsync(string Json, object userState) {
            if ((this.Insert_Tr_SnOperationCompleted == null)) {
                this.Insert_Tr_SnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsert_Tr_SnOperationCompleted);
            }
            this.InvokeAsync("Insert_Tr_Sn", new object[] {
                        Json}, this.Insert_Tr_SnOperationCompleted, userState);
        }
        
        private void OnInsert_Tr_SnOperationCompleted(object arg) {
            if ((this.Insert_Tr_SnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Insert_Tr_SnCompleted(this, new Insert_Tr_SnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Delete_SAP_PO_Tr_Sn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Delete_SAP_PO_Tr_Sn(string Json) {
            object[] results = this.Invoke("Delete_SAP_PO_Tr_Sn", new object[] {
                        Json});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_SAP_PO_Tr_SnAsync(string Json) {
            this.Delete_SAP_PO_Tr_SnAsync(Json, null);
        }
        
        /// <remarks/>
        public void Delete_SAP_PO_Tr_SnAsync(string Json, object userState) {
            if ((this.Delete_SAP_PO_Tr_SnOperationCompleted == null)) {
                this.Delete_SAP_PO_Tr_SnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_SAP_PO_Tr_SnOperationCompleted);
            }
            this.InvokeAsync("Delete_SAP_PO_Tr_Sn", new object[] {
                        Json}, this.Delete_SAP_PO_Tr_SnOperationCompleted, userState);
        }
        
        private void OnDelete_SAP_PO_Tr_SnOperationCompleted(object arg) {
            if ((this.Delete_SAP_PO_Tr_SnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_SAP_PO_Tr_SnCompleted(this, new Delete_SAP_PO_Tr_SnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TrSn_Barcode_Import", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TrSn_Barcode_Import(string ListJson, string Json, string STOCK_YEAR) {
            object[] results = this.Invoke("TrSn_Barcode_Import", new object[] {
                        ListJson,
                        Json,
                        STOCK_YEAR});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TrSn_Barcode_ImportAsync(string ListJson, string Json, string STOCK_YEAR) {
            this.TrSn_Barcode_ImportAsync(ListJson, Json, STOCK_YEAR, null);
        }
        
        /// <remarks/>
        public void TrSn_Barcode_ImportAsync(string ListJson, string Json, string STOCK_YEAR, object userState) {
            if ((this.TrSn_Barcode_ImportOperationCompleted == null)) {
                this.TrSn_Barcode_ImportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTrSn_Barcode_ImportOperationCompleted);
            }
            this.InvokeAsync("TrSn_Barcode_Import", new object[] {
                        ListJson,
                        Json,
                        STOCK_YEAR}, this.TrSn_Barcode_ImportOperationCompleted, userState);
        }
        
        private void OnTrSn_Barcode_ImportOperationCompleted(object arg) {
            if ((this.TrSn_Barcode_ImportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TrSn_Barcode_ImportCompleted(this, new TrSn_Barcode_ImportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Delete_SAP_PO_Tr_Sn_All", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Delete_SAP_PO_Tr_Sn_All(string Json) {
            object[] results = this.Invoke("Delete_SAP_PO_Tr_Sn_All", new object[] {
                        Json});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_SAP_PO_Tr_Sn_AllAsync(string Json) {
            this.Delete_SAP_PO_Tr_Sn_AllAsync(Json, null);
        }
        
        /// <remarks/>
        public void Delete_SAP_PO_Tr_Sn_AllAsync(string Json, object userState) {
            if ((this.Delete_SAP_PO_Tr_Sn_AllOperationCompleted == null)) {
                this.Delete_SAP_PO_Tr_Sn_AllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_SAP_PO_Tr_Sn_AllOperationCompleted);
            }
            this.InvokeAsync("Delete_SAP_PO_Tr_Sn_All", new object[] {
                        Json}, this.Delete_SAP_PO_Tr_Sn_AllOperationCompleted, userState);
        }
        
        private void OnDelete_SAP_PO_Tr_Sn_AllOperationCompleted(object arg) {
            if ((this.Delete_SAP_PO_Tr_Sn_AllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_SAP_PO_Tr_Sn_AllCompleted(this, new Delete_SAP_PO_Tr_Sn_AllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetSeqTrSnAndInsertCompletedEventHandler(object sender, GetSeqTrSnAndInsertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSeqTrSnAndInsertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSeqTrSnAndInsertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Get_Tr_SnCompletedEventHandler(object sender, Get_Tr_SnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Tr_SnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Tr_SnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Get_Tr_Sn_LocIdCompletedEventHandler(object sender, Get_Tr_Sn_LocIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Tr_Sn_LocIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Tr_Sn_LocIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Get_tr_sn_currentCompletedEventHandler(object sender, Get_tr_sn_currentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_tr_sn_currentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_tr_sn_currentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void UPDATE_TR_SNCompletedEventHandler(object sender, UPDATE_TR_SNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UPDATE_TR_SNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UPDATE_TR_SNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Insert_Tr_SnCompletedEventHandler(object sender, Insert_Tr_SnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Insert_Tr_SnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Insert_Tr_SnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Delete_SAP_PO_Tr_SnCompletedEventHandler(object sender, Delete_SAP_PO_Tr_SnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_SAP_PO_Tr_SnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_SAP_PO_Tr_SnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void TrSn_Barcode_ImportCompletedEventHandler(object sender, TrSn_Barcode_ImportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TrSn_Barcode_ImportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TrSn_Barcode_ImportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Delete_SAP_PO_Tr_Sn_AllCompletedEventHandler(object sender, Delete_SAP_PO_Tr_Sn_AllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_SAP_PO_Tr_Sn_AllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_SAP_PO_Tr_Sn_AllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591