//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace WMS_Client.ZPI_PIINTF_MES_SUBCON_PURCHASE {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZPI_PIINTF_MES_SUBCON_PURCHASE.PortTypeBinding", Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPI_PIINTF_MES_SUBCON_PURCHASEService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZPI_PIINTF_MES_SUBCON_PURCHASEOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZPI_PIINTF_MES_SUBCON_PURCHASEService() {
            this.Url = global::WMS_Client.Properties.Settings.Default.WMS_Client_ZPI_PIINTF_MES_SUBCON_PURCHASE_ZPI_PIINTF_MES_SUBCON_PURCHASEService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZPI_PIINTF_MES_SUBCON_PURCHASECompletedEventHandler ZPI_PIINTF_MES_SUBCON_PURCHASECompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", RequestNamespace="urn:sap-com:document:sap:rfc:functions", ResponseElementName="ZPI_PIINTF_MES_SUBCON_PURCHASE.Response", ResponseNamespace="urn:sap-com:document:sap:rfc:functions", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("E_MESSAGE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZPP_S_MESSAGE ZPI_PIINTF_MES_SUBCON_PURCHASE([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string I_EBELN, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] ref ZPP_S_SUBCON_PURCHASE[] T_SUBCON_PURCHASE) {
            object[] results = this.Invoke("ZPI_PIINTF_MES_SUBCON_PURCHASE", new object[] {
                        I_EBELN,
                        T_SUBCON_PURCHASE});
            T_SUBCON_PURCHASE = ((ZPP_S_SUBCON_PURCHASE[])(results[1]));
            return ((ZPP_S_MESSAGE)(results[0]));
        }
        
        /// <remarks/>
        public void ZPI_PIINTF_MES_SUBCON_PURCHASEAsync(string I_EBELN, ZPP_S_SUBCON_PURCHASE[] T_SUBCON_PURCHASE) {
            this.ZPI_PIINTF_MES_SUBCON_PURCHASEAsync(I_EBELN, T_SUBCON_PURCHASE, null);
        }
        
        /// <remarks/>
        public void ZPI_PIINTF_MES_SUBCON_PURCHASEAsync(string I_EBELN, ZPP_S_SUBCON_PURCHASE[] T_SUBCON_PURCHASE, object userState) {
            if ((this.ZPI_PIINTF_MES_SUBCON_PURCHASEOperationCompleted == null)) {
                this.ZPI_PIINTF_MES_SUBCON_PURCHASEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZPI_PIINTF_MES_SUBCON_PURCHASEOperationCompleted);
            }
            this.InvokeAsync("ZPI_PIINTF_MES_SUBCON_PURCHASE", new object[] {
                        I_EBELN,
                        T_SUBCON_PURCHASE}, this.ZPI_PIINTF_MES_SUBCON_PURCHASEOperationCompleted, userState);
        }
        
        private void OnZPI_PIINTF_MES_SUBCON_PURCHASEOperationCompleted(object arg) {
            if ((this.ZPI_PIINTF_MES_SUBCON_PURCHASECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZPI_PIINTF_MES_SUBCON_PURCHASECompleted(this, new ZPI_PIINTF_MES_SUBCON_PURCHASECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPP_S_SUBCON_PURCHASE {
        
        private string bUKRSField;
        
        private string lIFNRField;
        
        private string bSARTField;
        
        private string fRGZUField;
        
        private string eBELNField;
        
        private string eBELPField;
        
        private string pSTYPField;
        
        private string lOEKZField;
        
        private string mATNRField;
        
        private string lGORTField;
        
        private decimal mENGEField;
        
        private bool mENGEFieldSpecified;
        
        private string eINDTField;
        
        private string rEVLVField;
        
        private string rSNUMField;
        
        private string rSPOSField;
        
        private string mATNR_SUBField;
        
        private string mAKTXField;
        
        private string wERKSField;
        
        private string lGORT_SUBField;
        
        private decimal bDMNGField;
        
        private bool bDMNGFieldSpecified;
        
        private string bWARTField;
        
        private string zZINSMTDField;
        
        private string sCHGTField;
        
        private string dUMPSField;
        
        private string kZKUPField;
        
        private string aLPGRField;
        
        private decimal eWAHRField;
        
        private bool eWAHRFieldSpecified;
        
        private string xLOEKField;
        
        private decimal bOM_MENGEField;
        
        private bool bOM_MENGEFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BSART {
            get {
                return this.bSARTField;
            }
            set {
                this.bSARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FRGZU {
            get {
                return this.fRGZUField;
            }
            set {
                this.fRGZUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELN {
            get {
                return this.eBELNField;
            }
            set {
                this.eBELNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELP {
            get {
                return this.eBELPField;
            }
            set {
                this.eBELPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PSTYP {
            get {
                return this.pSTYPField;
            }
            set {
                this.pSTYPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOEKZ {
            get {
                return this.lOEKZField;
            }
            set {
                this.lOEKZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LGORT {
            get {
                return this.lGORTField;
            }
            set {
                this.lGORTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal MENGE {
            get {
                return this.mENGEField;
            }
            set {
                this.mENGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MENGESpecified {
            get {
                return this.mENGEFieldSpecified;
            }
            set {
                this.mENGEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EINDT {
            get {
                return this.eINDTField;
            }
            set {
                this.eINDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REVLV {
            get {
                return this.rEVLVField;
            }
            set {
                this.rEVLVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RSNUM {
            get {
                return this.rSNUMField;
            }
            set {
                this.rSNUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RSPOS {
            get {
                return this.rSPOSField;
            }
            set {
                this.rSPOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATNR_SUB {
            get {
                return this.mATNR_SUBField;
            }
            set {
                this.mATNR_SUBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MAKTX {
            get {
                return this.mAKTXField;
            }
            set {
                this.mAKTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LGORT_SUB {
            get {
                return this.lGORT_SUBField;
            }
            set {
                this.lGORT_SUBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal BDMNG {
            get {
                return this.bDMNGField;
            }
            set {
                this.bDMNGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BDMNGSpecified {
            get {
                return this.bDMNGFieldSpecified;
            }
            set {
                this.bDMNGFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BWART {
            get {
                return this.bWARTField;
            }
            set {
                this.bWARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZINSMTD {
            get {
                return this.zZINSMTDField;
            }
            set {
                this.zZINSMTDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SCHGT {
            get {
                return this.sCHGTField;
            }
            set {
                this.sCHGTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DUMPS {
            get {
                return this.dUMPSField;
            }
            set {
                this.dUMPSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KZKUP {
            get {
                return this.kZKUPField;
            }
            set {
                this.kZKUPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ALPGR {
            get {
                return this.aLPGRField;
            }
            set {
                this.aLPGRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal EWAHR {
            get {
                return this.eWAHRField;
            }
            set {
                this.eWAHRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EWAHRSpecified {
            get {
                return this.eWAHRFieldSpecified;
            }
            set {
                this.eWAHRFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string XLOEK {
            get {
                return this.xLOEKField;
            }
            set {
                this.xLOEKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal BOM_MENGE {
            get {
                return this.bOM_MENGEField;
            }
            set {
                this.bOM_MENGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BOM_MENGESpecified {
            get {
                return this.bOM_MENGEFieldSpecified;
            }
            set {
                this.bOM_MENGEFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPP_S_MESSAGE {
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ZPI_PIINTF_MES_SUBCON_PURCHASECompletedEventHandler(object sender, ZPI_PIINTF_MES_SUBCON_PURCHASECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZPI_PIINTF_MES_SUBCON_PURCHASECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZPI_PIINTF_MES_SUBCON_PURCHASECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZPP_S_MESSAGE Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZPP_S_MESSAGE)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public ZPP_S_SUBCON_PURCHASE[] T_SUBCON_PURCHASE {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZPP_S_SUBCON_PURCHASE[])(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591